### ISSUE TITLE
apply for multi-DOF robot manipulator

### ISSUE THREAD

**Issue by TBetterman** [SimoneRosset/ProgettoRobotica#1]
Hi, does this project can applied to multi-DOF robot manipulator, such as 6-DOF ur robot?

**Comment by rossettisimone** [comment]
I'm too sorry for the very late reply, probably I missed some emails. 
This solution is thought to work only on 2 DOF planar manipulators, but for sure you can extrapolate the concept and apply this algorithm to higher DOF manipulators.
